# Generated by Django 5.1.5 on 2025-01-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="uuid",
        ),
        migrations.AddField(
            model_name="paciente",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
