# Generated by Django 5.1.5 on 2025-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0002_remove_paciente_uuid_paciente_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="codigo",
            field=models.CharField(blank=True, default="", max_length=6, null=True),
        ),
    ]
