# Generated by Django 5.1.5 on 2025-01-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0003_paciente_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
