# Generated by Django 5.1.5 on 2025-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidar', '0004_alter_paciente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
