# Generated by Django 5.1.5 on 2025-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidar', '0005_alter_paciente_created_at_alter_paciente_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cadastro_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
