# Generated by Django 5.1.5 on 2025-02-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0006_paciente_cadastro_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="cadastro_ativo",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("S", "Solteiro(a)"),
                    ("C", "Casado(a)"),
                    ("D", "Divorciado(a)"),
                    ("V", "Viúvo(a)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")], max_length=50
            ),
        ),
    ]
