# Generated by Django 5.1.5 on 2025-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0007_alter_paciente_cadastro_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="outras_dependencias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="responsavel_pagamento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
